apiVersion: v1
kind: Secret
metadata:
  name: authsystem-secrets
type: Opaque
data:
  # Base64 encoded values
  JWT_SECRET_KEY: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  DB_PASSWORD: U3Ryb25nLlB3ZC0xMjM=
